# Generated by Django 5.2.9 on 2026-01-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='salario_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tiene_salario',
            field=models.BooleanField(default=False),
        ),
    ]
