# Generated by Django 5.2.9 on 2026-01-02 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0002_doctor_salario_mensual_doctor_tiene_salario'),
        ('pacientes', '0001_initial'),
        ('tratamientos', '0002_tratamiento_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='doctores.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AtencionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_comision', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión aplicado al momento de la atención', max_digits=5, null=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='atenciones.atencion')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tratamientos.tratamiento')),
            ],
        ),
    ]
