# Generated by Django 5.2.9 on 2026-01-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atenciondetalle',
            name='confirmado',
            field=models.BooleanField(default=False, help_text='Confirmado por el doctor'),
        ),
        migrations.AddField(
            model_name='atenciondetalle',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atenciondetalle',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
