# Generated by Django 5.2.9 on 2026-01-03 01:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0002_atenciondetalle_confirmado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atenciondetalle',
            old_name='precio_unitario',
            new_name='precio_base',
        ),
        migrations.AddField(
            model_name='atenciondetalle',
            name='aplica_iva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atenciondetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='atenciondetalle',
            name='iva_calculado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='atenciondetalle',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='atenciondetalle',
            name='total_calculado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
