# Generated by Django 5.2.9 on 2026-01-03 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0003_rename_precio_unitario_atenciondetalle_precio_base_and_more'),
        ('doctores', '0002_doctor_salario_mensual_doctor_tiene_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='doctores.doctor'),
        ),
        migrations.AlterField(
            model_name='atenciondetalle',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
