# Generated by Django 5.2.9 on 2026-01-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0004_alter_atencion_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='estado',
            field=models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado')], default='EN_PROCESO', max_length=20),
        ),
    ]
