# Generated by Django 5.2.9 on 2026-01-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0005_atencion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='validado',
            field=models.BooleanField(default=False, help_text='Si es True, la atención está conciliada y bloqueada.'),
        ),
    ]
