# Generated by Django 5.2.9 on 2026-01-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='historia_clinica',
            field=models.PositiveIntegerField(blank=True, help_text='Número de historia clínica física', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_principal',
            field=models.CharField(choices=[('ORT', 'Ortodoncia'), ('CIR', 'Cirugía'), ('CAL', 'Calzas'), ('END', 'Endodoncia'), ('GEN', 'General')], default='GEN', help_text='Tipo de tratamiento principal del paciente', max_length=3),
        ),
    ]
