# Generated by Django 5.2.9 on 2026-01-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_historia_clinica_paciente_tipo_principal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['historia_clinica'], 'verbose_name': 'Paciente / Cliente', 'verbose_name_plural': 'Pacientes / Clientes'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tipo_principal',
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_identificacion',
            field=models.CharField(default='0000000000', max_length=13, unique=True, verbose_name='Cédula / RUC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CED', 'Cédula'), ('RUC', 'RUC')], default='CED', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historia_clinica',
            field=models.CharField(default='SIN-FICHA', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
