# Generated by Django 5.2.17 on 2026-08-07 03:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_options_remove_paciente_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos_pacientes/%Y/%m/', verbose_name='Fotografía')),
                ('categoria', models.CharField(choices=[('EXTRAORAL_FRONTAL', 'Extraoral Frontal'), ('EXTRAORAL_PERFIL', 'Extraoral Perfil'), ('INTRAORAL_FRONTAL', 'Intraoral Frontal'), ('OCLUSAL_SUP', 'Oclusal Superior'), ('OCLUSAL_INF', 'Oclusal Inferior'), ('RADIOGRAFIA', 'Radiografía / RX'), ('OTRA', 'Otra')], default='EXTRAORAL_FRONTAL', max_length=30, verbose_name='Categoría / Ángulo')),
                ('etapa', models.CharField(choices=[('INICIAL', 'Inicial (Antes)'), ('DIAGNOSTICO', 'Diagnóstico'), ('AVANCE', 'Avance de Tratamiento'), ('FINAL', 'Final (Después)'), ('RETENCION', 'Retención')], default='INICIAL', max_length=20, verbose_name='Etapa del Tratamiento')),
                ('fecha_toma', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la Fotografía')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas / Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Fotografía de Paciente',
                'verbose_name_plural': 'Fotografías de Pacientes',
                'ordering': ['-fecha_toma', '-fecha_registro'],
            },
        ),
    ]
