# Generated by Django 5.2.9 on 2026-01-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='codigo',
            field=models.CharField(default='TEMP001', help_text='Código interno del tratamiento (ej: LD-001)', max_length=20),
            preserve_default=False,
        ),
    ]
