# Generated by Django 5.2.9 on 2026-01-03 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atenciones', '0002_atenciondetalle_confirmado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('forma_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TR', 'Transferencia'), ('TC', 'Tarjeta'), ('AB', 'Abono')], max_length=2)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, help_text='Referencia de transferencia o voucher', max_length=100)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='atenciones.atencion')),
            ],
        ),
    ]
