# Generated by Django 5.2.9 on 2026-01-02 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0002_doctor_salario_mensual_doctor_tiene_salario'),
        ('tratamientos', '0002_tratamiento_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de comisión (ej: 40.00)', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='doctores.doctor')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='tratamientos.tratamiento')),
            ],
            options={
                'unique_together': {('doctor', 'tratamiento')},
            },
        ),
    ]
